import type { Project } from "@/types/project";

export const placeholderProjects: Project[] = [
  {
    id: "issue-tracker",
    title: "Issue Tracker",
    description: "A FastAPI and React app for tracking and triaging project issues.",
    homepageUrl: null,
    githubRepo: "example/issue-tracker",
    languages: ["Python", "TypeScript"],
    topics: ["fastapi", "react", "postgres"],
    techKeywords: ["FastAPI", "React", "PostgreSQL", "Docker"],
    purposeKeywords: ["issue tracking", "project management"],
  },
  {
    id: "issue-tracker-rabbitmq",
    title: "Issue Tracker (RabbitMQ edition)",
    description: "Same issue tracker, rebuilt with an async worker queue for notifications.",
    homepageUrl: null,
    githubRepo: "example/issue-tracker-rabbitmq",
    languages: ["Python"],
    topics: ["rabbitmq", "fastapi", "async"],
    techKeywords: ["FastAPI", "RabbitMQ", "Docker"],
    purposeKeywords: ["issue tracking", "background jobs"],
  },
  {
    id: "ai-philosophy",
    title: "AI Philosophy",
    description: "An educational site visualizing core ideas in AI philosophy through interactive diagrams.",
    homepageUrl: "https://example.com/aiphilosophy",
    githubRepo: "example/aiphilosophy",
    languages: ["TypeScript"],
    topics: ["education", "visualization"],
    techKeywords: ["Next.js", "AWS", "Turso"],
    purposeKeywords: ["education", "data visualization"],
  },
  {
    id: "k8s-rag",
    title: "k8s RAG",
    description:
      "A retrieval-augmented generation service deployed on Kubernetes, built to explore running an LLM-backed search pipeline as a set of independently scalable microservices with their own ingress, autoscaling, and observability stack.",
    homepageUrl: null,
    githubRepo: "example/k8s-rag",
    languages: ["Python"],
    topics: ["kubernetes", "rag", "llm"],
    techKeywords: ["Kubernetes", "Python", "Vector DB"],
    purposeKeywords: ["search", "retrieval augmented generation"],
  },
  {
    id: "scalable-scraper",
    title: "Scalable Scraper",
    description: "A distributed web scraper that fans work out across worker nodes.",
    homepageUrl: null,
    githubRepo: "example/scalable-scraper",
    languages: ["Python"],
    topics: ["scraping", "distributed-systems"],
    techKeywords: ["Python", "Docker", "Redis"],
    purposeKeywords: ["web scraping", "data collection"],
  },
  {
    id: "balance-app",
    title: "Balance App",
    description: "A life-balance coaching app that syncs with your calendar and uses Claude for suggestions.",
    homepageUrl: null,
    githubRepo: "example/balance-app",
    languages: ["Python", "TypeScript"],
    topics: ["fastapi", "react", "ai"],
    techKeywords: ["FastAPI", "React", "Claude API", "Turso"],
    purposeKeywords: ["productivity", "coaching"],
  },
  {
    id: "portfolio1",
    title: "Portfolio Draft",
    description: "An early, unfinished portfolio site experiment.",
    homepageUrl: null,
    githubRepo: "example/portfolio1",
    languages: [],
    topics: [],
    techKeywords: [],
    purposeKeywords: [],
  },
];
